name: threading
version: 0.0.10
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Threading is an implementation of the cooperative, non-preemptive multitasking (software threads). Also can be used in conjunction with any third-party libraries for parallel computations (for the coordination and synchronization).
homepage: https://github.com/mezoni/threading
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  build_tools: any
  file_utils: any
  path: any
  test: any
